export const SELECT_USER = 'SELECT_USER'
export const GET_REPOS = 'GET_REPOS'
export const SELECT_REPO = 'SELECT_REPO'
export const GET_COMMITS = 'GET_COMMITS'
export const SHOW_LOADING = 'SHOW_LOADING'
export const RESET_STATE = 'RESET_STATE'
export const SET_ERROR = 'SET_ERROR'
export const RESET_COMMITS = 'RESET_COMMITS'
